className: sn.academy.food_delivery.source.FoodOrderSource
tenant: public
namespace: default
name: food-orders-source
topicName: "persistent://orders/inbound/food-orders"
parallelism: 1
processingGuarantees: ATLEAST_ONCE
resources:
  cpu: 0.5
  ram: 500000000