className: sn.academy.food_delivery.services.processing.PaymentService
tenant: public
namespace: default
name: payments-func
inputs:
  - "persistent://orders/validation/payments"
parallelism: 1
logTopic: persistent://public/default/payments-logs
autoAck: true
cleanupSubscription: true
subName: "payments-sub"
inputSpecs:
  persistent://orders/validation/payments:
    schemaType: "avro"
cpu: 0.2
ram: 200000000